# Generated by Django 5.1.7 on 2026-07-23 09:25

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('machine_number', models.CharField(max_length=50, unique=True, verbose_name='設備番号')),
                ('name', models.CharField(max_length=255, verbose_name='設備名')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='設置場所')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '設備',
                'verbose_name_plural': '設備',
                'ordering': ['machine_number'],
            },
        ),
    ]
