# Generated by Django 5.1.7 on 2025-07-31 03:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseSetting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="設定項目を一意に識別するキー（例: 'site_name'）。",
                        max_length=255,
                        unique=True,
                        verbose_name="項目名",
                    ),
                ),
                ("value", models.TextField(blank=True, help_text="設定項目の値。", verbose_name="設定値")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="この設定が現在有効であるかを示します。", verbose_name="有効"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="レコードが論理的に削除されているかを示します。",
                        verbose_name="削除フラグ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "基本設定",
                "verbose_name_plural": "基本設定",
                "ordering": ["name"],
            },
        ),
    ]
