# Generated by Django 5.1.7 on 2025-07-31 11:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvColumnMapping",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("item", "品番マスター"),
                            ("supplier", "サプライヤーマスター"),
                            ("warehouse", "倉庫マスター"),
                            ("purchase_order", "入庫予定"),
                            ("production_plan", "生産計画"),
                            ("parts_used", "使用部品"),
                        ],
                        help_text="どのデータのインポート設定かを選択します。",
                        max_length=50,
                        verbose_name="データ種別",
                    ),
                ),
                (
                    "csv_header",
                    models.CharField(
                        help_text="CSVファイルで使用される列のヘッダー名です。",
                        max_length=255,
                        verbose_name="CSVヘッダー名",
                    ),
                ),
                (
                    "model_field_name",
                    models.CharField(
                        help_text="対応するDjangoモデルのフィールド名です。",
                        max_length=255,
                        verbose_name="モデルフィールド名",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="画面表示やテンプレート生成時に使用される人間可読な名前です。",
                        max_length=255,
                        verbose_name="表示名",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="テンプレート生成や表示順を制御するための数値です。小さい順に表示されます。",
                        verbose_name="表示順",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="CSVインポート時にこの列が必須かどうかを示します。",
                        verbose_name="必須項目",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="このマッピングが現在有効であるかを示します。", verbose_name="有効"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "CSV列マッピング",
                "verbose_name_plural": "CSV列マッピング",
                "ordering": ["data_type", "order", "csv_header"],
                "unique_together": {("data_type", "csv_header"), ("data_type", "model_field_name")},
            },
        ),
    ]
