# Generated by Django 5.1.7 on 2025-08-01 04:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_csvcolumnmapping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvcolumnmapping",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="csvcolumnmapping",
            name="is_required",
        ),
        migrations.AddField(
            model_name="csvcolumnmapping",
            name="is_update_key",
            field=models.BooleanField(
                default=False,
                help_text="インポート時にこの列をキーとして既存データを検索し、更新します。",
                verbose_name="上書きキー",
            ),
        ),
        migrations.CreateModel(
            name="ModelDisplaySetting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("item", "品番マスター"),
                            ("supplier", "サプライヤーマスター"),
                            ("warehouse", "倉庫マスター"),
                            ("purchase_order", "入庫予定"),
                            ("production_plan", "生産計画"),
                            ("parts_used", "使用部品"),
                        ],
                        help_text="どのデータモデルの表示設定かを選択します。",
                        max_length=50,
                        verbose_name="データ種別",
                    ),
                ),
                (
                    "model_field_name",
                    models.CharField(
                        help_text="対応するDjangoモデルのフィールド名です。",
                        max_length=255,
                        verbose_name="モデルフィールド名",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="この項目を一覧画面に表示するかどうかを示します。",
                        verbose_name="表示フラグ",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="一覧画面での表示順を制御します。小さい順に表示されます。",
                        verbose_name="表示順",
                    ),
                ),
                (
                    "list_width",
                    models.PositiveIntegerField(
                        default=150,
                        help_text="一覧画面での列の幅をピクセル単位で指定します。",
                        verbose_name="一覧表示幅",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "モデル項目表示設定",
                "verbose_name_plural": "モデル項目表示設定",
                "ordering": ["data_type", "display_order"],
                "unique_together": {("data_type", "model_field_name")},
            },
        ),
    ]
