# Generated by Django 5.1.7 on 2025-08-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_remove_csvcolumnmapping_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeldisplaysetting",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="一覧画面で表示されるカスタム名。空の場合はモデルのverbose_nameが使用されます。",
                max_length=255,
                verbose_name="カスタム表示名",
            ),
        ),
    ]
