# Generated by Django 5.1.7 on 2025-08-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_remove_modeldisplaysetting_is_visible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeldisplaysetting",
            name="is_list_display",
            field=models.BooleanField(
                default=True, help_text="この項目を一覧画面に表示するかどうかを示します。", verbose_name="一覧表示"
            ),
        ),
        migrations.AddField(
            model_name="modeldisplaysetting",
            name="is_list_filter",
            field=models.BooleanField(
                default=False,
                help_text="この項目を管理画面のフィルタサイドバーに表示するかを示します。",
                verbose_name="フィルタ対象",
            ),
        ),
        migrations.AddField(
            model_name="modeldisplaysetting",
            name="is_search_field",
            field=models.BooleanField(
                default=False,
                help_text="この項目を管理画面の検索ボックスの対象にするかを示します。",
                verbose_name="検索対象",
            ),
        ),
        migrations.AlterField(
            model_name="csvcolumnmapping",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("item", "品番マスター"),
                    ("supplier", "サプライヤーマスター"),
                    ("warehouse", "倉庫マスター"),
                    ("purchase_order", "入庫予定"),
                    ("production_plan", "生産計画"),
                    ("parts_used", "使用部品"),
                    ("base_setting", "基本設定"),
                    ("csv_column_mapping", "CSV列マッピング"),
                    ("model_display_setting", "モデル項目表示設定"),
                ],
                help_text="どのデータのインポート設定かを選択します。",
                max_length=50,
                verbose_name="データ種別",
            ),
        ),
        migrations.AlterField(
            model_name="modeldisplaysetting",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("item", "品番マスター"),
                    ("supplier", "サプライヤーマスター"),
                    ("warehouse", "倉庫マスター"),
                    ("purchase_order", "入庫予定"),
                    ("production_plan", "生産計画"),
                    ("parts_used", "使用部品"),
                    ("base_setting", "基本設定"),
                    ("csv_column_mapping", "CSV列マッピング"),
                    ("model_display_setting", "モデル項目表示設定"),
                ],
                help_text="どのデータモデルの表示設定かを選択します。",
                max_length=50,
                verbose_name="データ種別",
            ),
        ),
    ]
