# Generated by Django 5.1.7 on 2025-08-03 04:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_modeldisplaysetting_search_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="QrCodeAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="アクションを一意に識別する名前。",
                        max_length=100,
                        unique=True,
                        verbose_name="アクション名",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="このアクションが何をするかの説明。", verbose_name="説明"),
                ),
                (
                    "qr_code_pattern",
                    models.CharField(
                        help_text="マッチング対象のQRコードの正規表現パターン。例: '^ITEM-.+'",
                        max_length=255,
                        verbose_name="QRコードパターン",
                    ),
                ),
                (
                    "script",
                    models.TextField(
                        help_text="QRコードがマッチした際に実行されるPythonスクリプト。", verbose_name="実行スクリプト"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="このアクションが現在有効であるかを示します。", verbose_name="有効"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "QRコードアクション",
                "verbose_name_plural": "QRコードアクション",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="csvcolumnmapping",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("item", "品番マスター"),
                    ("supplier", "サプライヤーマスター"),
                    ("warehouse", "倉庫マスター"),
                    ("purchase_order", "入庫予定"),
                    ("goods_receipt", "入庫実績"),
                    ("production_plan", "生産計画"),
                    ("parts_used", "使用部品"),
                    ("base_setting", "基本設定"),
                    ("csv_column_mapping", "CSV列マッピング"),
                    ("model_display_setting", "モデル項目表示設定"),
                    ("qr_code_action", "QRコードアクション"),
                ],
                help_text="どのデータのインポート設定かを選択します。",
                max_length=50,
                verbose_name="データ種別",
            ),
        ),
        migrations.AlterField(
            model_name="modeldisplaysetting",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("item", "品番マスター"),
                    ("supplier", "サプライヤーマスター"),
                    ("warehouse", "倉庫マスター"),
                    ("purchase_order", "入庫予定"),
                    ("goods_receipt", "入庫実績"),
                    ("production_plan", "生産計画"),
                    ("parts_used", "使用部品"),
                    ("base_setting", "基本設定"),
                    ("csv_column_mapping", "CSV列マッピング"),
                    ("model_display_setting", "モデル項目表示設定"),
                    ("qr_code_action", "QRコードアクション"),
                ],
                help_text="どのデータモデルの表示設定かを選択します。",
                max_length=50,
                verbose_name="データ種別",
            ),
        ),
    ]
