# Generated by Django 5.1.7 on 2025-08-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_alter_csvcolumnmapping_data_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvcolumnmapping",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("item", "品番マスター"),
                    ("inventory", "在庫"),
                    ("supplier", "サプライヤーマスター"),
                    ("warehouse", "倉庫マスター"),
                    ("purchase_order", "入庫予定"),
                    ("sales_order", "出庫予定"),
                    ("goods_receipt", "入庫実績"),
                    ("production_plan", "生産計画"),
                    ("parts_used", "使用部品"),
                    ("base_setting", "基本設定"),
                    ("csv_column_mapping", "CSV列マッピング"),
                    ("model_display_setting", "モデル項目表示設定"),
                    ("qr_code_action", "QRコードアクション"),
                    ("stock_movement", "入出庫履歴"),
                ],
                help_text="どのデータのインポート設定かを選択します。",
                max_length=50,
                verbose_name="データ種別",
            ),
        ),
        migrations.AlterField(
            model_name="modeldisplaysetting",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("item", "品番マスター"),
                    ("inventory", "在庫"),
                    ("supplier", "サプライヤーマスター"),
                    ("warehouse", "倉庫マスター"),
                    ("purchase_order", "入庫予定"),
                    ("sales_order", "出庫予定"),
                    ("goods_receipt", "入庫実績"),
                    ("production_plan", "生産計画"),
                    ("parts_used", "使用部品"),
                    ("base_setting", "基本設定"),
                    ("csv_column_mapping", "CSV列マッピング"),
                    ("model_display_setting", "モデル項目表示設定"),
                    ("qr_code_action", "QRコードアクション"),
                    ("stock_movement", "入出庫履歴"),
                ],
                help_text="どのデータモデルの表示設定かを選択します。",
                max_length=50,
                verbose_name="データ種別",
            ),
        ),
    ]
