# Generated by Django 5.1.7 on 2025-08-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_alter_csvcolumnmapping_data_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcodeaction",
            name="action_type",
            field=models.CharField(
                choices=[("regex", "正規表現で判定"), ("script", "スクリプトで判定")],
                default="regex",
                help_text="アクションをトリガーする条件のタイプを選択します。",
                max_length=10,
                verbose_name="アクションタイプ",
            ),
        ),
        migrations.AlterField(
            model_name="qrcodeaction",
            name="qr_code_pattern",
            field=models.CharField(
                blank=True,
                help_text="アクションタイプが「正規表現で判定」の場合に、マッチング対象となる正規表現パターン。例: '^ITEM-.+'",
                max_length=255,
                verbose_name="QRコードパターン",
            ),
        ),
        migrations.AlterField(
            model_name="qrcodeaction",
            name="script",
            field=models.TextField(
                help_text="QRコードがマッチした際、またはスクリプト判定で実行されるPythonスクリプト。",
                verbose_name="実行スクリプト",
            ),
        ),
    ]
