# Generated by Django 5.1.7 on 2025-09-12 09:48

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_qrcodeaction_action_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("task_id", models.CharField(max_length=255, unique=True, verbose_name="タスクID")),
                ("task_name", models.CharField(blank=True, max_length=255, verbose_name="タスク名")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待機中"),
                            ("STARTED", "実行中"),
                            ("SUCCESS", "成功"),
                            ("FAILURE", "失敗"),
                            ("REVOKED", "キャンセル済み"),
                        ],
                        default="PENDING",
                        max_length=50,
                        verbose_name="ステータス",
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0, verbose_name="進捗")),
                ("total", models.PositiveIntegerField(default=100, verbose_name="総数")),
                ("result", models.JSONField(blank=True, null=True, verbose_name="結果")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "非同期タスク",
                "verbose_name_plural": "非同期タスク",
                "ordering": ["-created_at"],
            },
        ),
    ]
