# Generated by Django 5.1.7 on 2026-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_asynctask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodeaction',
            name='script',
        ),
        migrations.AddField(
            model_name='qrcodeaction',
            name='action_name',
            field=models.CharField(choices=[('mark_as_received', '入庫としてマーク'), ('update_inventory', '在庫更新')], default='mark_as_received', help_text='実行するアクションを選択します。', max_length=50, verbose_name='アクション名（内部用）'),
        ),
        migrations.AlterField(
            model_name='qrcodeaction',
            name='action_type',
            field=models.CharField(choices=[('regex', '正規表現で判定')], default='regex', help_text='アクションをトリガーする条件のタイプを選択します。', max_length=10, verbose_name='アクションタイプ'),
        ),
    ]
