# Generated by Django 5.1.7 on 2026-07-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_qrcodeaction_script_qrcodeaction_action_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvcolumnmapping',
            name='data_type',
            field=models.CharField(choices=[('item', '品番マスター'), ('inventory', '在庫'), ('supplier', 'サプライヤーマスター'), ('warehouse', '倉庫マスター'), ('purchase_order', '入庫予定'), ('sales_order', '出庫予定'), ('goods_receipt', '入庫実績'), ('production_plan', '生産計画'), ('parts_used', '使用部品'), ('base_setting', '基本設定'), ('csv_column_mapping', 'CSV列マッピング'), ('model_display_setting', 'モデル項目表示設定'), ('qr_code_action', 'QRコードアクション'), ('stock_movement', '入出庫履歴'), ('customer', '顧客マスター'), ('work_center', 'ワークセンターマスター'), ('unit_cost', '標準単価')], help_text='どのデータのインポート設定かを選択します。', max_length=50, verbose_name='データ種別'),
        ),
        migrations.AlterField(
            model_name='modeldisplaysetting',
            name='data_type',
            field=models.CharField(choices=[('item', '品番マスター'), ('inventory', '在庫'), ('supplier', 'サプライヤーマスター'), ('warehouse', '倉庫マスター'), ('purchase_order', '入庫予定'), ('sales_order', '出庫予定'), ('goods_receipt', '入庫実績'), ('production_plan', '生産計画'), ('parts_used', '使用部品'), ('base_setting', '基本設定'), ('csv_column_mapping', 'CSV列マッピング'), ('model_display_setting', 'モデル項目表示設定'), ('qr_code_action', 'QRコードアクション'), ('stock_movement', '入出庫履歴'), ('customer', '顧客マスター'), ('work_center', 'ワークセンターマスター'), ('unit_cost', '標準単価')], help_text='どのデータモデルの表示設定かを選択します。', max_length=50, verbose_name='データ種別'),
        ),
    ]
