# Generated by Django 5.1.7 on 2026-09-05 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_planet_culc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('human', '通常ユーザー'), ('system', 'システム連携用')], default='human', help_text='通常ユーザーか、外部システム連携専用アカウントかの区分。', max_length=10, verbose_name='account type'),
        ),
        migrations.CreateModel(
            name='ApiTokenPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='トークン有効')),
                ('allowed_ips', models.TextField(blank=True, help_text='カンマまたは改行区切りでIPアドレスかCIDRを指定します。空欄の場合は制限しません。', verbose_name='接続許可IP')),
                ('scopes', models.JSONField(blank=True, default=list, help_text='空リストの場合は全アプリにアクセス可能です。', verbose_name='許可するAPIアプリ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token_policy', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
            ],
            options={
                'verbose_name': 'APIトークンポリシー',
                'verbose_name_plural': 'APIトークンポリシー',
            },
        ),
    ]
