# Generated by Django 5.1.7 on 2025-04-04 13:59

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=0)),
                ("reserved", models.IntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_allocatable", models.BooleanField(default=True)),
                ("item", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="master.item")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="master.warehouse")),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("order_number", models.CharField(max_length=20, unique=True)),
                ("quantity", models.PositiveIntegerField()),
                ("received_quantity", models.PositiveIntegerField(default=0)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("expected_arrival", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("received", "Received"), ("canceled", "Canceled")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="master.item")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="master.supplier")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="master.warehouse")),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("order_number", models.CharField(max_length=20, unique=True)),
                ("quantity", models.PositiveIntegerField()),
                ("shipped_quantity", models.PositiveIntegerField(default=0)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("expected_shipment", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("shipped", "Shipped"), ("canceled", "Canceled")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="master.item")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="master.warehouse")),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("incoming", "Incoming"), ("outgoing", "Outgoing"), ("used", "Used in production")],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="master.item")),
            ],
        ),
    ]
