# Generated by Django 5.1.7 on 2025-05-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="color_info",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="色情報"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_destination",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="納入先"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_source",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="納入元"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="instruction_document",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="指示書"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="is_first_time",
            field=models.BooleanField(default=False, verbose_name="初回"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="model_type",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="機種"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="parent_part_number",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="親品番"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="part_number",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="品番"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="product_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="品名"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="remarks1",
            field=models.TextField(blank=True, null=True, verbose_name="備考1"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="remarks2",
            field=models.TextField(blank=True, null=True, verbose_name="備考2"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="remarks3",
            field=models.TextField(blank=True, null=True, verbose_name="備考3"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="remarks4",
            field=models.TextField(blank=True, null=True, verbose_name="備考4"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="remarks5",
            field=models.TextField(blank=True, null=True, verbose_name="備考5"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="shipment_number",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="便番号"),
        ),
    ]
