# Generated by Django 5.1.7 on 2025-05-16 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_purchaseorder_color_info_and_more"),
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="item",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="master.item"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="master.supplier"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="warehouse",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="master.warehouse"),
        ),
    ]
