# Generated by Django 5.1.7 on 2025-05-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_purchaseorder_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="item",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="warehouse",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
