# Generated by Django 5.1.7 on 2025-05-16 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_inventory_item_alter_inventory_warehouse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="item",
            new_name="part_number",
        ),
        migrations.RenameField(
            model_name="stockmovement",
            old_name="item",
            new_name="part_number",
        ),
    ]
