# Generated by Django 5.1.7 on 2025-06-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_remove_stockmovement_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("incoming", "入庫"),
                    ("outgoing", "出庫"),
                    ("used", "生産使用"),
                    ("PRODUCTION_OUTPUT", "生産完了入庫"),
                    ("PRODUCTION_REVERSAL", "生産完了取消"),
                    ("adjustment", "在庫調整"),
                ],
                max_length=20,
            ),
        ),
    ]
