# Generated by Django 5.1.7 on 2025-07-31 23:26

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_remove_purchaseorder_received_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="有効フラグ"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="is_allocatable",
            field=models.BooleanField(default=True, verbose_name="引当可能フラグ"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="最終更新日時"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="棚番"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="part_number",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="品番"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="在庫数量"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="reserved",
            field=models.IntegerField(default=0, verbose_name="引当済数量"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="warehouse",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="倉庫"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="expected_arrival",
            field=models.DateTimeField(blank=True, null=True, verbose_name="入荷予定日時"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="is_first_time",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="初回"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="item",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="品目"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="発注日"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="発注番号"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="発注数量"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "未入庫"),
                    ("partially_received", "一部入庫"),
                    ("fully_received", "全量入庫済み"),
                    ("canceled", "キャンセル"),
                ],
                default="pending",
                max_length=20,
                null=True,
                verbose_name="ステータス",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="仕入先"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="expected_shipment",
            field=models.DateTimeField(blank=True, null=True, verbose_name="出庫予定日時"),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="受注日"),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="order_number",
            field=models.CharField(max_length=20, unique=True, verbose_name="受注番号"),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="出庫予定数量"),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="shipped_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="出庫済数量"),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("shipped", "Shipped"), ("canceled", "Canceled")],
                default="pending",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("incoming", "入庫"),
                    ("outgoing", "出庫"),
                    ("used", "生産使用"),
                    ("PRODUCTION_OUTPUT", "生産完了入庫"),
                    ("PRODUCTION_REVERSAL", "生産完了取消"),
                    ("adjustment", "在庫調整"),
                ],
                max_length=20,
                verbose_name="移動タイプ",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="part_number",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="品番"),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="数量"),
        ),
    ]
