# Generated by Django 5.1.7 on 2025-08-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_alter_inventory_id_alter_inventory_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="棚番"),
        ),
    ]
