# Generated by Django 5.1.7 on 2026-06-09 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_purchaseorder_received_quantity'),
        ('master', '0007_ensure_test_stub_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='inventory',
            name='part_number_rel',
            field=models.ForeignKey(blank=True, db_column='part_number', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.item', to_field='code', verbose_name='品番'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse_rel',
            field=models.ForeignKey(blank=True, db_column='warehouse', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.warehouse', to_field='warehouse_number', verbose_name='倉庫'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='part_number_rel',
            field=models.ForeignKey(blank=True, db_column='part_number', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.item', to_field='code', verbose_name='品番'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_rel',
            field=models.ForeignKey(blank=True, db_column='supplier', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.supplier', to_field='supplier_number', verbose_name='仕入先'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse_rel',
            field=models.ForeignKey(blank=True, db_column='warehouse', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.warehouse', to_field='warehouse_number', verbose_name='入庫倉庫'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='warehouse_rel',
            field=models.ForeignKey(blank=True, db_column='warehouse', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.warehouse', to_field='warehouse_number', verbose_name='入庫倉庫'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='item_rel',
            field=models.ForeignKey(blank=True, db_column='item', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.item', to_field='code', verbose_name='出庫対象（製品・材料）'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='warehouse_rel',
            field=models.ForeignKey(blank=True, db_column='warehouse', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.warehouse', to_field='warehouse_number', verbose_name='出庫倉庫'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='part_number_rel',
            field=models.ForeignKey(blank=True, db_column='part_number', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.item', to_field='code', verbose_name='品番'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse_rel',
            field=models.ForeignKey(blank=True, db_column='warehouse', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.warehouse', to_field='warehouse_number', verbose_name='倉庫'),
        ),
    ]
