# Generated by Django 5.1.7 on 2026-07-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_inventory_part_number_and_more'),
        ('master', '0007_ensure_test_stub_data'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('part_number_rel', 'warehouse_rel', 'location'), name='unique_inventory_part_warehouse_location'),
        ),
    ]
