# Generated by Django 5.1.7 on 2026-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_inventory_unique_inventory_part_warehouse_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='first_received_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='初回入庫日時'),
        ),
    ]
