# Generated by Django 5.1.7 on 2026-09-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_inventory_location_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivered_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='納品数'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='納品日'),
        ),
    ]
