# Generated by Django 5.1.7 on 2025-06-01 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryPurchaseEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="数量")),
                ("expected_date", models.DateField(verbose_name="入庫予定日")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備考")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="master.item", verbose_name="品番"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.supplier",
                        verbose_name="サプライヤー",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="master.warehouse", verbose_name="倉庫"
                    ),
                ),
            ],
            options={
                "verbose_name": "入庫予定",
                "verbose_name_plural": "入庫予定",
            },
        ),
    ]
