# Generated by Django 5.1.7 on 2025-06-01 23:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0002_inventorypurchaseentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InventoryPurchaseEntry",
        ),
    ]
