# Generated by Django 5.1.7 on 2025-06-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0003_delete_inventorypurchaseentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="default_location",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="デフォルト入庫棚番"),
        ),
        migrations.AddField(
            model_name="item",
            name="default_warehouse",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="デフォルト入庫倉庫"),
        ),
        migrations.AddField(
            model_name="item",
            name="provision_type",
            field=models.CharField(
                blank=True,
                choices=[("paid", "有償支給"), ("free", "無償支給"), ("none", "支給なし")],
                max_length=10,
                null=True,
                verbose_name="支給種別",
            ),
        ),
    ]
