# Generated by Django 5.1.7 on 2025-07-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0005_supplier_supplier_number_alter_supplier_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="provision_type",
            field=models.CharField(
                blank=True,
                choices=[("paid", "有償支給"), ("free", "無償支給"), ("none", "支給なし")],
                default="none",
                max_length=10,
                null=True,
                verbose_name="支給種別",
            ),
        ),
    ]
