# Generated by Django 5.1.7 on 2026-07-11 13:50

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_ensure_test_stub_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='顧客コード')),
                ('name', models.CharField(max_length=255, verbose_name='顧客名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='ワークセンターコード')),
                ('name', models.CharField(max_length=255, verbose_name='ワークセンター名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitCost',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='標準単価')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.PROTECT, related_name='unit_costs', to='master.item', to_field='code', verbose_name='品目')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item',), name='unique_unitcost_item')],
            },
        ),
    ]
