# Generated by Django 5.1.7 on 2026-07-12 01:30

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_customer_workcenter_unitcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='layout_cols',
            field=models.PositiveIntegerField(default=20, verbose_name='レイアウト列数'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='layout_rows',
            field=models.PositiveIntegerField(default=20, verbose_name='レイアウト行数'),
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, verbose_name='棚番')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='ロケーション名')),
                ('pos_x', models.PositiveIntegerField(verbose_name='X座標(列)')),
                ('pos_y', models.PositiveIntegerField(verbose_name='Y座標(行)')),
                ('width', models.PositiveIntegerField(default=1, verbose_name='幅(マス数)')),
                ('height', models.PositiveIntegerField(default=1, verbose_name='高さ(マス数)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='master.warehouse', verbose_name='倉庫')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_warehouse_location_code')],
            },
        ),
    ]
