# Generated by Django 5.1.7 on 2026-09-05 05:48

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_warehouse_layout_cols_warehouse_layout_rows_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='所要数量（製品1個あたり）')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(db_column='material', on_delete=django.db.models.deletion.PROTECT, related_name='bom_as_material', to='master.item', to_field='code', verbose_name='使用部品')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, related_name='bom_as_product', to='master.item', to_field='code', verbose_name='製品')),
            ],
            options={
                'verbose_name': '使用部品構成',
                'verbose_name_plural': '使用部品構成',
                'ordering': ['product__code', 'material__code'],
                'constraints': [models.UniqueConstraint(fields=('product', 'material'), name='unique_bom_product_material')],
            },
        ),
    ]
