# Generated by Django 5.1.7 on 2026-09-27 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_item_lead_time_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, related_name='bom_as_product', to='master.item', to_field='code', verbose_name='親品目（製品・中間品）'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='所要数量（親品目1個あたり）'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('material', 'Material'), ('intermediate', 'Intermediate')], max_length=20),
        ),
    ]
