# Generated by Django 5.1.7 on 2026-09-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_item_intermediate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
