# Generated by Django 5.1.7 on 2025-05-25 07:31

import django.db.models.deletion
import django.utils.timezone
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="検査項目を一意に識別するコード",
                        max_length=50,
                        unique=True,
                        verbose_name="検査項目コード",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="検査項目名")),
                ("description", models.TextField(blank=True, null=True, verbose_name="説明")),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("acceptance", "受入検査"),
                            ("in_process", "工程内検査"),
                            ("final", "最終検査"),
                            ("shipping", "出荷検査"),
                            ("patrol", "巡回検査"),
                        ],
                        max_length=20,
                        verbose_name="検査種別",
                    ),
                ),
                (
                    "target_object_type",
                    models.CharField(
                        choices=[
                            ("raw_material", "原材料"),
                            ("component", "部品"),
                            ("wip", "仕掛品"),
                            ("finished_good", "完成品"),
                            ("equipment", "設備"),
                            ("process", "工程"),
                        ],
                        max_length=20,
                        verbose_name="対象物タイプ",
                    ),
                ),
                (
                    "measurement_type",
                    models.CharField(
                        choices=[("qualitative", "定性判定"), ("quantitative", "定量測定")],
                        default="qualitative",
                        max_length=20,
                        verbose_name="測定タイプ",
                    ),
                ),
                ("specification_nominal", models.FloatField(blank=True, null=True, verbose_name="規格値（中心値）")),
                ("specification_upper_limit", models.FloatField(blank=True, null=True, verbose_name="規格上限値")),
                ("specification_lower_limit", models.FloatField(blank=True, null=True, verbose_name="規格下限値")),
                ("specification_unit", models.CharField(blank=True, max_length=50, null=True, verbose_name="単位")),
                (
                    "expected_qualitative_result",
                    models.CharField(
                        blank=True,
                        help_text="例: OK, 異常なし",
                        max_length=100,
                        null=True,
                        verbose_name="期待結果（定性）",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効フラグ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "検査項目マスター",
                "verbose_name_plural": "検査項目マスター",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="InspectionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("inspected_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="検査日時")),
                (
                    "part_number",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="品番"),
                ),
                (
                    "lot_number",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="ロット番号"),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="シリアル番号"),
                ),
                (
                    "related_order_type",
                    models.CharField(
                        blank=True,
                        help_text="例: 製造指示, 購買発注, 出荷指示",
                        max_length=50,
                        null=True,
                        verbose_name="関連オーダータイプ",
                    ),
                ),
                (
                    "related_order_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True, verbose_name="関連オーダー番号"
                    ),
                ),
                ("quantity_inspected", models.PositiveIntegerField(blank=True, null=True, verbose_name="検査数量")),
                ("measured_value_numeric", models.FloatField(blank=True, null=True, verbose_name="測定値（定量）")),
                (
                    "result_qualitative",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="結果（定性）"),
                ),
                (
                    "judgment",
                    models.CharField(
                        choices=[
                            ("pass", "合格"),
                            ("fail", "不合格"),
                            ("pending", "保留"),
                            ("conditional_pass", "条件付き合格"),
                        ],
                        max_length=20,
                        verbose_name="判定結果",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True, verbose_name="備考")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="quality/inspection_attachments/%Y/%m/%d/",
                        verbose_name="添付ファイル",
                    ),
                ),
                (
                    "equipment_used",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="使用設備/測定器"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="検査員",
                    ),
                ),
                (
                    "inspection_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="quality.inspectionitem",
                        verbose_name="検査項目",
                    ),
                ),
            ],
            options={
                "verbose_name": "検査実績",
                "verbose_name_plural": "検査実績",
                "ordering": ["-inspected_at", "inspection_item"],
            },
        ),
    ]
