# Generated by Django 5.1.7 on 2025-05-18 09:37

import django.db.models.deletion
import django.utils.timezone
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionPlan",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("plan_name", models.CharField(max_length=255, verbose_name="計画名")),
                ("product_code", models.CharField(max_length=100, verbose_name="製品コード (仮)")),
                ("planned_quantity", models.PositiveIntegerField(verbose_name="計画数量")),
                ("planned_start_datetime", models.DateTimeField(verbose_name="計画開始日時")),
                ("planned_end_datetime", models.DateTimeField(verbose_name="計画終了日時")),
                ("actual_start_datetime", models.DateTimeField(blank=True, null=True, verbose_name="実績開始日時")),
                ("actual_end_datetime", models.DateTimeField(blank=True, null=True, verbose_name="実績終了日時")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "未着手"),
                            ("IN_PROGRESS", "進行中"),
                            ("COMPLETED", "完了"),
                            ("ON_HOLD", "保留"),
                            ("CANCELLED", "中止"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True, verbose_name="備考")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "verbose_name": "生産計画",
                "verbose_name_plural": "生産計画",
                "ordering": ["-planned_start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="PartsUsed",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("part_code", models.CharField(max_length=100, verbose_name="部品コード (仮)")),
                ("quantity_used", models.PositiveIntegerField(verbose_name="使用数量")),
                ("used_datetime", models.DateTimeField(default=django.utils.timezone.now, verbose_name="使用日時")),
                ("remarks", models.TextField(blank=True, null=True, verbose_name="備考")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "production_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_used",
                        to="production.productionplan",
                        verbose_name="生産計画",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用部品",
                "verbose_name_plural": "使用部品",
                "ordering": ["-used_datetime"],
            },
        ),
        migrations.CreateModel(
            name="MaterialAllocation",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("material_code", models.CharField(max_length=100, verbose_name="材料コード (仮)")),
                ("allocated_quantity", models.PositiveIntegerField(verbose_name="引当数量")),
                (
                    "allocation_datetime",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="引当日時"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ALLOCATED", "引当済"), ("ISSUED", "出庫済"), ("RETURNED", "返却済")],
                        default="ALLOCATED",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True, verbose_name="備考")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "production_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_allocations",
                        to="production.productionplan",
                        verbose_name="生産計画",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料引当",
                "verbose_name_plural": "材料引当",
                "ordering": ["-allocation_datetime"],
            },
        ),
        migrations.CreateModel(
            name="WorkProgress",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("process_step", models.CharField(max_length=100, verbose_name="工程ステップ")),
                ("start_datetime", models.DateTimeField(blank=True, null=True, verbose_name="開始日時")),
                ("end_datetime", models.DateTimeField(blank=True, null=True, verbose_name="終了日時")),
                ("quantity_completed", models.PositiveIntegerField(default=0, verbose_name="完了数量")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "未開始"),
                            ("IN_PROGRESS", "進行中"),
                            ("COMPLETED", "完了"),
                            ("PAUSED", "一時停止"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True, verbose_name="備考")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作業者",
                    ),
                ),
                (
                    "production_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_progresses",
                        to="production.productionplan",
                        verbose_name="生産計画",
                    ),
                ),
            ],
            options={
                "verbose_name": "作業進捗",
                "verbose_name_plural": "作業進捗",
                "ordering": ["production_plan", "start_datetime"],
            },
        ),
    ]
