# Generated by Django 5.1.7 on 2025-05-19 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="production_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referencing_production_plans",
                to="production.productionplan",
                verbose_name="参照生産計画",
            ),
        ),
    ]
