# Generated by Django 5.1.7 on 2025-05-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0003_alter_partsused_production_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsused",
            name="warehouse",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="使用倉庫"),
        ),
    ]
