# Generated by Django 5.1.7 on 2026-05-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_workprogress_actual_reported_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialallocation',
            name='warehouse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='引当倉庫'),
        ),
    ]
