# Generated by Django 5.1.7 on 2026-06-09 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_ensure_test_stub_data'),
        ('production', '0006_materialallocation_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialallocation',
            name='material_code',
        ),
        migrations.RemoveField(
            model_name='materialallocation',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='partsused',
            name='part_code',
        ),
        migrations.RemoveField(
            model_name='partsused',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='product_code',
        ),
        migrations.AddField(
            model_name='materialallocation',
            name='material',
            field=models.ForeignKey(blank=True, db_column='material_code', limit_choices_to={'item_type': 'material'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.item', to_field='code', verbose_name='材料'),
        ),
        migrations.AddField(
            model_name='materialallocation',
            name='warehouse_rel',
            field=models.ForeignKey(blank=True, db_column='warehouse', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.warehouse', to_field='warehouse_number', verbose_name='引当倉庫'),
        ),
        migrations.AddField(
            model_name='partsused',
            name='part',
            field=models.ForeignKey(blank=True, db_column='part_code', limit_choices_to={'item_type': 'material'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.item', to_field='code', verbose_name='部品'),
        ),
        migrations.AddField(
            model_name='partsused',
            name='warehouse_rel',
            field=models.ForeignKey(blank=True, db_column='warehouse', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.warehouse', to_field='warehouse_number', verbose_name='使用倉庫'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_code', limit_choices_to={'item_type': 'product'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.item', to_field='code', verbose_name='製品'),
        ),
    ]
