# Generated by Django 5.1.7 on 2026-07-11 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_remove_materialallocation_material_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workprogress',
            constraint=models.UniqueConstraint(fields=('production_plan', 'process_step'), name='unique_workprogress_plan_process_step'),
        ),
    ]
