# Generated by Django 5.1.7 on 2026-09-27 10:44

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_item_intermediate_type'),
        ('production', '0008_workprogress_unique_workprogress_plan_process_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialallocation',
            name='allocation_type',
            field=models.CharField(choices=[('NORMAL', '通常'), ('ADDITIONAL', '追加出庫')], default='NORMAL', max_length=20, verbose_name='引当区分'),
        ),
        migrations.AlterField(
            model_name='materialallocation',
            name='material',
            field=models.ForeignKey(blank=True, db_column='material_code', limit_choices_to={'item_type__in': ('material', 'intermediate')}, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.item', to_field='code', verbose_name='材料'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_code', limit_choices_to={'item_type__in': ('product', 'intermediate')}, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.item', to_field='code', verbose_name='製品'),
        ),
        migrations.CreateModel(
            name='ProductionPlanMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='所要数量（製品1個あたり）')),
                ('required_quantity', models.PositiveIntegerField(verbose_name='所要数量（計画全体）')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('material', models.ForeignKey(db_column='material_code', limit_choices_to={'item_type__in': ('material', 'intermediate')}, on_delete=django.db.models.deletion.PROTECT, to='master.item', to_field='code', verbose_name='部品')),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.productionplan', verbose_name='生産計画')),
            ],
            options={
                'verbose_name': '生産計画所要部品',
                'verbose_name_plural': '生産計画所要部品',
                'ordering': ['material__code'],
                'constraints': [models.UniqueConstraint(fields=('production_plan', 'material'), name='unique_plan_material')],
            },
        ),
    ]
