# Generated by Django 5.1.7 on 2026-09-27 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_migrate_parts_used_to_plan_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_plans', to='production.productionplan', verbose_name='親生産計画'),
        ),
        migrations.AddField(
            model_name='productionplanmaterial',
            name='supply_method',
            field=models.CharField(blank=True, choices=[('', '未決定'), ('STOCK', '在庫を使う'), ('CHILD_PLAN', '子計画を立てる')], default='', max_length=20, verbose_name='手配方法'),
        ),
    ]
